### This is the Terraform-generated dev-build.yml workflow for the wcd2reshare-dev app repository ###
name: Dev Build and Deploy lambda Container
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    paths-ignore:
      - '.github/**'

jobs:
  deploy:
    name: Dev Deploy lambda Container
    uses: mitlibraries/.github/.github/workflows/lambda-shared-deploy-dev.yml@main
    secrets: inherit
    with:
      AWS_REGION: "us-east-1"
      GHA_ROLE: "wcd2reshare-gha-dev"
      ECR: "wcd2reshare-dev"
      FUNCTION: "wcd2reshare-dev"
