### This is the Terraform-generated prod-promote.yml workflow for the wcd2reshare-prod app repository ###
name: Prod Promote Lambda Container
on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  deploy:
    name: Prod Promote Lambda Container
    uses: mitlibraries/.github/.github/workflows/lambda-shared-promote-prod.yml@main
    secrets: inherit
    with:
      AWS_REGION: "us-east-1"
      GHA_ROLE_STAGE: wcd2reshare-gha-stage
      GHA_ROLE_PROD: wcd2reshare-gha-prod
      ECR_STAGE: "wcd2reshare-stage"
      ECR_PROD: "wcd2reshare-prod"
      FUNCTION: "wcd2reshare-prod"
 