### This is the Terraform-generated stage-build.yml workflow for the wcd2reshare-stage repository ###
name: Stage Build and Deploy Lambda Container
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - '.github/**'

jobs:
  deploy:
    name: Stage Deploy Lambda Container
    uses: mitlibraries/.github/.github/workflows/lambda-shared-deploy-stage.yml@main
    secrets: inherit
    with:
      AWS_REGION: "us-east-1"
      GHA_ROLE: "wcd2reshare-gha-stage"
      ECR: "wcd2reshare-stage"
      FUNCTION: "wcd2reshare-stage"
