### This is the Terraform-generated dev-build.yml workflow for the wcd2reshare-stage app repository ###
### If this is a Lambda repo, uncomment the FUNCTION line at the end of the document     ###
### If the container requires any additional pre-build commands, uncomment and edit      ###
### the PREBUILD line at the end of the document.                                        ###
name: Stage Container Build and Deploy
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - '.github/**'

jobs:
  deploy:
    name: Stage Container Deploy
    uses: mitlibraries/.github/.github/workflows/ecr-shared-deploy-stage.yml@main
    secrets: inherit
    with:
      AWS_REGION: "us-east-1"
      GHA_ROLE: "wcd2reshare-gha-stage"
      ECR: "wcd2reshare-stage"
      FUNCTION: "wcd2reshare-stage"
      # PREBUILD: 
